openapi: 3.0.1
info:
  title: eHealth Transaction API
  description: API specification for eHealth Transaction API
    
    
    Environment - **DEV**


    - Read more about eHealth API Manifest [here](https://ehealthapimanifest.docs.apiary.io/#introduction/interacting-with-api)


    - Read more about transactions [here](https://e-health-ua.atlassian.net/wiki/spaces/EH/pages/604995700/Transactions)


    - Transactions are asynchronous. [Prefer header](https://tools.ietf.org/html/rfc7240#section-4.1) with "respose-async" is required. Otherwise "405 Method Not Allowed" will be returned.


    - Transaction should only contain data for a single patient.


    - Transactions only support creating resources with POST.


    - When validating the resource the context of the validation should consider both, existing resources from DB and resources passed in the same transaction, so the circular references could be successfully processed.


    - The same request (with the same body) can be sent multiple times, but a new transaction will not start processing until the previous one is complete.
    
    - Please ignore all the "$$ref" properties. It is a [known issue](https://github.com/swagger-api/swagger-ui/issues/4924) of the rendering tool.
    
  contact: {}
  version: '1.0'
servers:
- url: http://ehealth.edenlabllc.com/
  variables: {}
tags:
  - name: Transaction
    description: Please check '[FHIR Specification](https://www.hl7.org/fhir/http.html#transaction)' on transactions.
  - name: StructureDefinition

paths:
  /fhir:
    post:
      summary: Submit Transaction
      tags:
        - Transaction
      description: This endpoint is used to kick of the trasaction with the Transaction Bundle. The response for success is 202 with the Content-Location in header by which the transaction response can be polled.
      operationId: SubmitTransaction
      parameters:
      - name: Prefer
        in: header
        description: The required header for the async mode.
        required: true
        schema:
          type: string
          example: respond-async
      - name: Content-Type
        in: header
        description: The content type.
        required: true
        schema:
          type: string
          example: application/json
      requestBody:
        description: The transaction request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
            examples:    
              successful:
                $ref: '#/components/examples/TransactionRequest'
        required: true
      responses:
        202:
          description: Successful transaction kick off.
          headers: 
            Content-Location:
              description: The location of the job (like /api/Job/8b8619de-2e56-47d9-8386-5f8e255f3755)
              schema:
                type: string
              example:  /api/Job/8b8619de-2e56-47d9-8386-5f8e255f3755
          content:
            application/json:
              schema: {}
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: structure
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: structure
                    text: "Profile http://ehealth.ua/fhir/StructureDefinition/TransactionBundle, Element 'entry': minimum required = 1, but only found 0" 
        405:
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-supported
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-supported
                    text: Only asynchronous mode for transactions is supported.
         
                    
  /fhir/Job/{id}:
    get:
      summary: Get Transaction Job
      tags:
        - Transaction
      description: |
        This endpoint should be used to get the Job that was created as a result of Transaction Kick-Off.


        * `Response 202` indicates that the transaction is being processed and the response isn't ready yet.
        
        * `Response 303` indicates will return the actual transaction response
      operationId: GetTransactionJob
      parameters:
      - name: id
        in: path
        description: the id of the Job
        required: true
        schema:
          type: string
          example: 8b8619de-2e56-47d9-8386-5f8e255f3755
      - name: Content-Type
        in: header
        description: The content type.
        required: true
        schema:
          type: string
          example: application/json
      responses:
        202:
          description: The job.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              example:
                status: accepted
        303:
          description: The job. Either output property with reference to Bundle or error property with reference to OperationOutcome should be provided.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              example:
                status: processed
                output:
                  reference: Bundle/f2d1462c-7aab-4062-9136-0b3a18d7c82c
                  type: Bundle
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-found
                    text: A resource with such id was not found.
                    
  /fhir/Bundle/{id}:
    get:
      summary: Get Transaction Response
      tags:
        - Transaction
      description: |
        This endpoint should be used to get the results of the successful transaction execution as TransactionResponse

      operationId: GetTransactionResponse
      parameters:
      - name: id
        in: path
        description: the id of the Transaction Response Bundle
        required: true
        style: simple
        schema:
          type: string
          example: f6a272fe-6f32-423f-b1f5-dad6f269e1e2
      - name: Content-Type
        in: header
        description: The content type.
        required: true
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: The transaction response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-found
                    text: A resource with such id was not found.

  /fhir/OperationOutcome/{id}:
    get:
      summary: Get OperationOutcome by id.
      tags:
        - Transaction
      description: |
        This endpoint should be used to get the results of the unsuccessful transaction execution as OperationOutcome.

      operationId: GetOperationOutcome
      parameters:
      - name: id
        in: path
        description: the id of the OperationOutcome
        required: true
        style: simple
        schema:
          type: string
          example: ffe29872-5464-4ae5-baaf-84ee7f08bea7
      - name: Content-Type
        in: header
        description: The content type.
        required: true
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: The OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: structure
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: structure
                    text: "Profile http://ehealth.ua/fhir/StructureDefinition/inpatient-condition, Element 'Condition.subject': minimum required = 1, but only found 0" 
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-found
                    text: A resource with such id was not found.
                    
  /fhir/StructureDefinition:
    post:
      summary: Create StructureDefinition
      tags:
        - StructureDefinition
      description: This endpoint is used to create StructureDefinition. The created SD can then be used from resources as a profile.
      operationId: PostStructureDefinition
      parameters:
      - name: Content-Type
        in: header
        description: The content type.
        required: true
        schema:
          type: string
          example: application/json
      requestBody:
        description: StructureDefinition.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StructureDefinition'
          # examples:    
          #    successful:
          #      $ref: '#/components/examples/StructureDefinition'
        required: true
      responses:
        202:
          description: Created StructureDefinition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StructureDefinition'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: structure
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: structure
                    text: "SD http://ehealth.ua/fhir/StructureDefinition/StructureDefinition, Element 'url': minimum required = 1, but only found 0" 
        422:
          description: Unprocessable Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: bad-syntax
                    text: A resource cannot be parsed.  

  /fhir/StructureDefinition/{id}:
    get:
      summary: Get StructureDefinition by id.
      tags:
        - StructureDefinition
      description: |
        This endpoint is used to get the StructureDefinition by id.
      operationId: GetStructureDefinition
      parameters:
      - name: id
        in: path
        description: The id of the StructureDefinition
        required: true
        style: simple
        schema:
          type: string
          example: ffe29872-5464-4ae5-baaf-84ee7f08bea7
      responses:
        200:
          description: The StructureDefinition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StructureDefinition'
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-found
                    text: A resource with such id was not found.
    put:
      summary: Update StructureDefinition.
      tags:
        - StructureDefinition
      description: |
        This endpoint is used to update the StructureDefinition.
      operationId: UpdateStructureDefinition
      parameters:
      - name: id
        in: path
        description: The id of the StructureDefinition
        required: true
        style: simple
        schema:
          type: string
          example: ffe29872-5464-4ae5-baaf-84ee7f08bea7
      - name: Content-Type
        in: header
        description: The content type.
        required: true
        schema:
          type: string
          example: application/json
      requestBody:
        description: StructureDefinition.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StructureDefinition'
          # examples:    
          #    successful:
          #      $ref: '#/components/examples/StructureDefinition'
        required: true
      responses:
        200:
          description: The StructureDefinition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StructureDefinition'
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-found
                    text: A resource with such id was not found.  
        422:
          description: Unprocessable Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: bad-syntax
                    text: A resource cannot be parsed.    
    delete:
      summary: Delete StructureDefinition.
      tags:
        - StructureDefinition
      description: |
        This endpoint is used to delete the StructureDefinition.
      operationId: DeleteStructureDefinition
      parameters:
      - name: id
        in: path
        description: The id of the StructureDefinition
        required: true
        style: simple
        schema:
          type: string
          example: ffe29872-5464-4ae5-baaf-84ee7f08bea7
      responses:
        204:
          description: Successfully deleted
        404:
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                - code: not-found
                  details:
                    coding:
                    - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
                      code: not-found
                    text: A resource with such id was not found.  
                    
components:
  schemas:
    OperationOutcome:
      description: See FHIR '[OperationOutcome](https://www.hl7.org/fhir/operationoutcome.html)'
      type: object
      properties:
        resourceType:
          type: string
          minLength: 1
        issue:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required: [severity, code]
            properties:
              severity:
                type: string
                minLength: 1
                description: Issue severity.
              code:
                type: string
                minLength: 1
                description: Error or warning code.
              details:
                $ref: '#/components/schemas/CodeableConcept'
                description: Additional diagnostic information about the issue
          description: Issues associated with the action
      required: [resourceType]
      example:
        resourceType: OperationOutcome
        issue: 
        - severity: error
          code: structure
          details:
            coding:
            - system: http://ehealth.ua/fhir/ValueSet/operation-outcome
              code: structure
            text: "Profile http://ehealth.ua/fhir/StructureDefinition/TransactionBundle, Element 'entry': minimum required = 1, but only found 0" 
          
    Quantity:
      title: Quantity
      type: object
      properties:
        value:
          type: number
          example: 0
        comparator:
          type: string
          example: '>'
        unit:
          type: string
          description: for future use
          example: mg
        system:
          type: string
          example: eHealth/units
        code:
          type: string
          example: mg
      required: [value, system, code]
      example: 
        value: 0
        comparator: '>'
        unit: mg
        system: eHealth/units
        code: mg
          
    Range:
      title: Range
      type: object
      properties:
        low:
          $ref: '#/components/schemas/Quantity'
        high:
          $ref: '#/components/schemas/Quantity'
          
    Period:
      title: Period
      description: See FHIR '[Period](https://www.hl7.org/fhir/datatypes.html#Period)'
      type: object
      properties:
        start:
          type: string
          format: datetime
          description: Starting time with inclusive boundary.
        end:
          type: string
          format: datetime
          description: End time with inclusive boundary, if not ongoing.

    Job:
      title: Job
      type: object
      properties:
        status:
          type: string
          enum: [accepted, processed]
          description: eHealth/job_statuses
        output:
          $ref: '#/components/schemas/Reference'
          description: The output for the job resulted in success.
        error:
          $ref: '#/components/schemas/Reference'
          description: The output for the job resulted in error.
      required: [status]
      example:
        status: processed
        output:
          reference: Bundle/f2d1462c-7aab-4062-9136-0b3a18d7c82c
          type: Bundle
    
    TransactionRequest:
      title: Bundle (TransactionRequest)
      description: See FHIR '[Bundle](https://www.hl7.org/fhir/bundle.html)'
      type: object
      properties:
        resourceType:
          type: string
          description: The resource type.
        type:
          type: string
          description: The bundle type.
        meta:
          $ref: '#/components/schemas/Meta'
        subject:
          $ref: '#/components/schemas/Reference'
        entry:
          type: array
          minItems: 1
          items:
            description: Entries (resources) in the bundle.
            type: object
            properties:
              resource:
                oneOf:
                - $ref: '#/components/schemas/Encounter'
                - $ref: '#/components/schemas/Observation'
                - $ref: '#/components/schemas/Condition'
              request:
                type: object
                description: Additional execution information.
                properties:
                  method:
                    type: string
                    description: HTTP action to be executed for this entry.
                  url:
                    type: string
                    description: The URL for this entry, relative to the root (the address to which the request is posted).
                required: [method, url]
        signature:
          type: string
          description: signed content of the bundle.
          example: ew0KICAicGVyaW9kIjogew0KIC...
      required: [resourceType, type, entry, subject, meta]
      
    TransactionResponse:
      title: Bundle (TransactionResponse)
      description: See FHIR '[Bundle](https://www.hl7.org/fhir/bundle.html)'
      type: object
      properties:
        resourceType:
          type: string
        type:
          type: string
          description: The bundle type.
        meta:
          $ref: '#/components/schemas/Meta'
        id:
          type: string
          description: the id of the Transaction Response Bundle
        entry:
          description: Entries (resources) in the bundle.
          type: array
          minItems: 1
          items:
            type: object
            properties:
              fullUrl:
                type: string
                description: URI for resource (Absolute URL server address).
              resource:
                $ref: '#/components/schemas/Encounter'
              response:
                description: Results of execution. 
                type: object
                properties:
                  status:
                    type: string
                    description: Status response code
                    required: [status]
      required: [resourceType, type, id, entry, meta]
      example:
        resourceType: Bundle
        type: transaction-response
        meta:
          profile:
          - https://ehealth.ua/fhir/StructureDefinition/transaction-response-bundle
        id: 8afe3988-1517-48de-aa76-b017e9d79bcc
        entry:
        - fulllUrl: http://ehealth.edenlabllc.com/api/Encounter/465fb6fe-2dea-4b8a-9ef7-58379d1eaab0
          resource:
              $ref: '#/components/schemas/Encounter'
          response: 
            status: 201 Created
        
    Meta:
      title: Meta
      description: See FHIR '[Meta](https://www.hl7.org/fhir/resource.html#Meta)'
      type: object
      properties:
        profile:
          type: array
          items:
            type: string
          description: The StructureDefinition to validate against.
      required: [profile]
      
    Identifier:
      title: Identifier
      description: See FHIR '[Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier)'. Custom profile for Identifier is used - system and value are required.
      type: object
      properties:
        system:
          type: string
          description: The namespace for the identifier value.
        value:
          type: string
          description: The value that is unique.
      required: [system, value]
      
    Reference:
      title: Reference
      description: See FHIR '[Reference](https://www.hl7.org/fhir/references.html#Reference)'. Reference should be either literal ("reference" is required), or logical ("identifier" is required)
      type: object
      properties:
        reference:
          type: string
          description: Literal reference, Relative, internal or absolute URL.
        type:
          type: string
          description: Type the reference refers to (e.g. "Observation")
        identifier:
          $ref: '#/components/schemas/Identifier'
      required: [reference]
      example:
        reference: http://ehealth.ua/fhir/Observation/9183a36b-4d45-4244-9339-63d81cd08d9c
        type: Observation
          
    CodeableConcept:
      title: CodeableConcept
      description: See FHIR '[CodeableConcept](https://www.hl7.org/fhir/datatypes.html#CodeableConcept)'
      type: object
      properties:
        coding:
          type: array
          items:
            $ref: '#/components/schemas/Coding'
          description: ''
        text:
          type: string    
      required: [coding]
      

    Coding:
      title: Coding
      description: See FHIR '[Coding](https://www.hl7.org/fhir/datatypes.html#Coding)'
      type: object
      properties:
        system:
          type: string
          description: Identity of the terminology system
        code:
          type: string
          description: Symbol in syntax defined by the system
      required: [system, code]
      example:
        system: eHealth/encounter_classes
        code: AMB
  
    Encounter:
      title: Encounter
      description: See FHIR '[Encounter](https://www.hl7.org/fhir/encounter.html)'
      required:
      - meta
      - resourceType
      - id
      - class
      - subject
      - status
      type: object
      properties:
        resourceType:
          type: string
          description: The resource type.
        id:
          type: string
          description: Id of the resource.
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        status:
          type: string
          description: CodeSystem http://ehealth.edenlabllc.com/CodeSystem/eHealth/encounter_statuses
        class:
          $ref: '#/components/schemas/Coding'        
        date:
          type: string
          format: datetime
        subject:
          $ref: '#/components/schemas/Reference' 
        participant: 
          type: array
          items:
            type: object
            properties:
              type:
                $ref: '#/components/schemas/CodeableConcept'
              period: 
                $ref: '#/components/schemas/Period'
              individual:
                $ref: '#/components/schemas/Reference'               
        episodeOfCare:
          $ref: '#/components/schemas/Reference'
        basedOn:
          $ref: '#/components/schemas/Reference'
        type:
          $ref: '#/components/schemas/CodeableConcept'
        serviceProvider:
          $ref: '#/components/schemas/Reference'
        diagnoses:
          type: array
          items:
            type: object
            properties:
              condition:
                $ref: '#/components/schemas/Reference'
              use:
                $ref: '#/components/schemas/CodeableConcept'
              rank:
                type: number
                description: Ranking of the diagnosis. Max value = 10 (for each role type)
          description: The list of diagnosis relevant to this encounter
        location:
          $ref: '#/components/schemas/Reference'
        hospitalization:
          type: object
          properties:
            admitSource:
              $ref: '#/components/schemas/CodeableConcept'
            reAdmission:
              $ref: '#/components/schemas/CodeableConcept'
        priority:
          $ref: '#/components/schemas/CodeableConcept'
      example:
        resourceType: Encounter
        meta:
          profile:
          - http://ehealth.ua/fhir/StructureDefinition/Encounter
        id: 465fb6fe-2dea-4b8a-9ef7-58379d1eaab0
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233       
        participant:
        - type:
            coding:
              - system: http://ehealth.edenlabllc.com/CodeSystem/participant-type
                code: PPRF
          individual:
            identifier: 
              system: https://ehealth.ua/Employees
              value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        status: finished
        date: 2018-08-02T10:45:16.000Z
        episodeOfCare:
          reference: http://ehealth.ua/fhir/EpisodeOfCare/9183a36b-4d45-4244-9339-63d81cd08d9c
        basedOn:
          reference: http://ehealth.ua/fhir/ServiceRequest/9183a36b-4d45-4244-9339-63d81cd08d9c
        class:
          system: http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_classes
          code: PHC
        type:
          coding:
          - system: http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_types
            code: field
        serviceProvider:
          reference: http://ehealth.ua/fhir/Organization/9183a36b-4d45-4244-9339-63d81cd08d9c
        diagnoses:
        - condition:
            reference: http://ehealth.ua/fhir/Condition/9183a36b-4d45-4244-9339-63d81cd08d9c
          use:
            coding:
            - system: http://ehealth.ua/fhir/CodeSystem/eHealth/diagnosis_roles
              code: primary
          rank: 1
        location:
          reference: http://ehealth.ua/fhir/Location/9183a36b-4d45-4244-9339-63d81cd08d9c
        hospitalization:
          admitSource:
            coding:
            - system: http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_admit_source
              code: EMD
          reAdmission:
            coding:
            - system: http://ehealth.edenlabllc.com/CodeSystem/eHealth/diagnosis_readmission
              code: R
        priority: 
          coding:
            - system: http://ehealth.edenlabllc.com/CodeSystem/eHealth/encounter_priority
              code: R
            
            
    Observation:
      title: Observation
      description: See FHIR '[Observation](https://www.hl7.org/fhir/observation.html)'
      required:
      - id
      - meta
      - resourceType
      - subject
      - status
      - code
      - encounter
      - performer
      - issued
      type: object
      properties:
        resourceType:
          type: string
          example: Observation
        id:
          type: string
          example: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        subject:
          $ref: '#/components/schemas/Reference' 
        performer:
          $ref: '#/components/schemas/Reference'        
        status:
          type: string
          description: CodeSystem http://ehealth.edenlabllc.com/CodeSystem/observation_statuses
        partOf: 
          $ref: '#/components/schemas/Reference'
        category:
          $ref: '#/components/schemas/CodeableConcept'
        code:
          $ref: '#/components/schemas/CodeableConcept'
        encounter:
          $ref: '#/components/schemas/Reference'
        effectiveDateTime:
          type: string
          format: datetime
        issued:
          type: string
          format: datetime
        interpretation:
          $ref: '#/components/schemas/CodeableConcept'
        note:
          type: object
          properties:
            text:
              type: string
        bodySite:
          $ref: '#/components/schemas/CodeableConcept'
        method:
          $ref: '#/components/schemas/CodeableConcept'
        valueQuantity: 
          $ref: '#/components/schemas/Quantity'
        referenceRanges:
          type: array
          items:
            type: object
            properties:
              low:
                $ref: '#/components/schemas/Quantity'
              high:
                $ref: '#/components/schemas/Quantity'
              type:
                $ref: '#/components/schemas/CodeableConcept'
              applies_to:
                $ref: '#/components/schemas/CodeableConcept'
              age:
                $ref: '#/components/schemas/Range'
              text:
                type: string
          description: Provides guide for interpretation
        reactionOn:
          $ref: '#/components/schemas/Reference'
        components:
          type: object
          properties:
            code:
              $ref: '#/components/schemas/CodeableConcept'
            interpretation:
              $ref: '#/components/schemas/CodeableConcept'
            reference_ranges:
              type: array
              items:
                type: object
                properties:
                  low:
                    $ref: '#/components/schemas/Quantity'
                  high:
                    $ref: '#/components/schemas/Quantity'
                  type:
                    $ref: '#/components/schemas/CodeableConcept'
                  applies_to:
                    $ref: '#/components/schemas/CodeableConcept'
                  age:
                    $ref: '#/components/schemas/Range'
                  text:
                    type: string
      example:        
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        resourceType: Observation
        meta:
          profile:
          - http://ehealth.ua/fhir/StructureDefinition/Observation
        status: valid
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233
        performer:
          identifier: 
            system: https://ehealth.ua/Employees
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e     
        partOf:
          reference: http://ehealth.ua/fhir/DiagnosticReport/9183a36b-4d45-4244-9339-63d81cd08d9c
        category: 
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_categories
                code: survey
        code: 
          - coding: 
              - system: http://loinc.org
                code: 10010-7
        encounter:
          reference: http://ehealth.ua/fhir/Encounter/9183a36b-4d45-4244-9339-63d81cd08d9c
        effectiveDateTime: 2013-04-02T09:30:10+01:00
        issued: 2013-04-02T09:30:10+01:00
        interpretation:
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_interpretations
                code: L
        note:
          text: "To see the world in a grain of sand, and to see heaven in a wild flower, hold infinity in the palm of your hands, and eternity in an hour."
        bodySite:
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/body_sites
                code: 106004
        method:
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_method
                code: 115341008
        valueQuantity:
          value: 0
          comparator: >
          unit: mg
          system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
          code: mg
        referenceRange:
          low:
            value: 0
            comparator: >
            unit: mg
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
            code: mg
          high:
            value: 0
            comparator: >
            unit: mg
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
            code: mg
          type:
            - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/reference_range_types
                code: normal
          appliesTo:
            - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/reference_range_applications
                code: Male
          age:
            low:
              value: 18
              comparator: >
              unit: years
            high:
              value: 35
              comparator: <
              unit: years
        component:
          code:
            - coding: 
              - system: http://loinc.org
                code: 10569-2
          valueQuantity:
            value: 0
            comparator: >
            unit: mg
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
            code: mg
          interpretation:
            - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_interpretations
                code: L

    Condition:
      title: Condition
      description: See FHIR '[Condition](https://www.hl7.org/fhir/condition.html)'
      required:
      - id
      - resourceType
      - encounter
      - recorder
      - asserter
      - code
      - onsetDate
      type: object
      properties:
        resourceType:
          type: string
          example: Condition
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        id:
          type: string
          example: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        subject:
          $ref: '#/components/schemas/Reference'
        recorder:
          $ref: '#/components/schemas/Reference'
        asserter:
          $ref: '#/components/schemas/Reference'
        code:
          $ref: '#/components/schemas/CodeableConcept'
        clinicalStatus:
          $ref: '#/components/schemas/CodeableConcept'
        verificationStatus:
          $ref: '#/components/schemas/CodeableConcept'
        severity:
          $ref: '#/components/schemas/CodeableConcept'
        bodySites:
          type: array
          items:
            $ref: '#/components/schemas/CodeableConcept'
          description: ''
        onsetDate:
          type: string
          example: 2018-10-08T09:46:37.694Z
        recordedDate:
          type: string
          example: 2018-10-08T09:46:37.694Z
        stage:
          type: object
          properties:
            summary:
              $ref: '#/components/schemas/CodeableConcept'
          required: [summary]
        evidence:
          type: array
          items:
            type: object
            properties:
              code:
                type: array
                items:
                  $ref: '#/components/schemas/CodeableConcept'
                description: ''
              detail:
                type: array
                items:
                  $ref: '#/components/schemas/Reference'
          description: Supporting evidence
      example:
        resourceType: Condition
        meta:
          profile:
          - http://ehealth.ua/fhir/StructureDefinition/Condition
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233
        recorder:
          identifier: 
            system: https://ehealth.ua/Employees
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        asserter:
          identifier: 
            system: https://ehealth.ua/Employees
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        encounter:
          reference: http://ehealth.ua/fhir/Encounter/9183a36b-4d45-4244-9339-63d81cd08d9c
        code:
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/ICD10
            code: A00.0
        clinicalStatus: 
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_clinical_statuses
            code: active
        verificationStatus: 
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_verification_statuses
            code: confirmed
        severity:
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_severities
            code: mild
        bodySite:
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/body_sites
            code: 106004
        onsetDateTime: 2018-10-08T09:46:37.694Z
        recordedDate: 2018-10-08T09:46:37.694Z
        stage:
          summary:
            coding:
              system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_stages
              code: 260998006
        evidences:
          code:
            coding:
              system: http://ehealth.ua/fhir/CodeSystem/eHealth/ICPC2/reasons
              code: B41
          detail:
            reference: http://ehealth.ua/fhir/Observation/9183a36b-4d45-4244-9339-63d81cd08d9c
    
    ContactPoint:
      title: ContactPoint
      description: See FHIR '[ContactPoint](https://www.hl7.org/fhir/datatypes.html#ContactPoint)'
      type: object
      properties:
        system:
          type: string
          enum: [phone,fax,email,pager,url,sms,other]
          description: '[ContactPointSystem](https://www.hl7.org/fhir/valueset-contact-point-system.html)'
        value:
          type: string
          description: The actual contact point details.
        use: 
          type: string
          enum: [home,work,temp,old,mobile]
          description: '[ContactPointUse](https://www.hl7.org/fhir/valueset-contact-point-use.html)'
        rank:
          type: integer
          description: Specify preferred order of use (1 = highest).
        period:
          $ref: '#/components/schemas/Period'
  
    ContactDetail:
      title: ContactDetail
      description: See FHIR '[ContactDetail](https://www.hl7.org/fhir/metadatatypes.html#ContactDetail)'
      type: object
      properties:
        name:
          type: string
          description: Name of an individual to contact.
        telecom:
          $ref: '#/components/schemas/ContactPoint'

    UsageContext:
      title: UsageContext
      description: See FHIR '[UsageContext](https://www.hl7.org/fhir/metadatatypes.html#UsageContext)'
      type: object
      properties:
        code:
          $ref: '#/components/schemas/Coding'
        valueCodeableConcept:
          $ref: '#/components/schemas/CodeableConcept'
        valueQuantity:
          $ref: '#/components/schemas/Quantity'
        valueRange:
          $ref: '#/components/schemas/Range'
        valueReference:
          $ref: '#/components/schemas/Reference'
          
    ElementDefinition:
      title: ElementDefinition
      type: object
      description: See FHIR '[ElementDefinition](http://www.hl7.org/fhir/elementdefinition.html#ElementDefinition)'
      required:
      - path
      properties:
        path:
          type: string
          description: Path of the element in the hierarchy of elements.
            
    StructureDefinition:
      title: StructureDefinition
      description: See FHIR '[StructureDefinition](http://www.hl7.org/fhir/structuredefinition.html)' and '[profiling](https://www.hl7.org/fhir/profiling.html)'
      required:
      - meta
      - resourceType
      - id
      - url
      - name
      - status
      - kind
      - abstract
      - type
      type: object
      properties:
        resourceType:
          type: string
          description: The resource type.
        id:
          type: string
          description: Id of the resource.
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        url:
          type: string
          description:   Canonical identifier for this structure definition, represented as a URI (globally unique).
        identifier:
          type: string
          description: Additional identifier for the structure definition. 
        version:
          type: string
          description: Business version of the structure definition.     
        name:
          type: string
          description: Name for this structure definition (computer friendly).
        title:
          type: string
          description: Name for this structure definition (human friendly).
        status:
          type: string
          enum: [draft, active, retired, unknown]
          description: The pulication status.
        expertimental:
          type: boolean
          description: For testing purposes, not real usage.
        date:
          type: string
          format: datetime
          description: Date last changed.
        publisher:
          type: string
          description: Name of the publisher (organization or individual).
        contactDetail:
          type: array
          items:
            $ref: '#/components/schemas/ContactDetail'
          description: Contact details for the publisher
        description:
          type: string
          description: Natural language description of the structure definition.
        useContext:
          type: array
          items:
            $ref: '#/components/schemas/UsageContext'
          description: The context that the content is intended to support.
        jurisdiction:
          $ref: '#/components/schemas/CodeableConcept'
        purpose:
          type: string
          description: Why this structure definition is defined.
        copyright:
          type: string
          description: Use and/or publishing restrictions.
        keyword:
          type: array
          items:
            $ref: '#/components/schemas/Coding'
          description: Assist with indexing and finding. System - [UseCodes](http://www.hl7.org/fhir/valueset-definition-use.html).  
        fhirVersion:
          type: string
          description: FHIR Version this StructureDefinition targets. ValueSet - [FHIRVersion](http://www.hl7.org/fhir/valueset-FHIR-version.html).     
        mapping: 
          type: object
          description: External specification that the content is mapped to.
          properties: 
            identity:
              type: string
              description: Internal id when this mapping is used.
            uri: 
              type: string
              description: Identifies what this mapping refers to.
            name:
              type: string
              description: Names what this mapping refers to.
            comment: 
              type: string
              description: Versions, Issues, Scope limitations etc.
            kind:
              type: string
              enum: [primitive-type,complex-type,resource,logical]
              description: '[Structure Definition Kind](http://www.hl7.org/fhir/valueset-structure-definition-kind.html)'
          required: [kind]
        abstract:
          type: boolean
          description: Whether the structure is abstract.
        context:
          type: object
          description: If an extension, where it can be used in instances.
          required: [type,expression]
          properties:
            type:
              type: string
              enum: [fhirpath,element,extension]
              description: '[ExtensionContextType](http://www.hl7.org/fhir/valueset-extension-context-type.html)'
            expression:
              type: string
              description: Where the extension can be used in instances.
        contextInvariants:
          type: string
          description: FHIRPath invariants - when the extension can be used.
        type:
          type: string
          description: Type defined or constrained by this structure. [DefinedTypes](http://www.hl7.org/fhir/valueset-defined-types.html)
        baseDefinition:
          type: string
          description: Definition that this type is constrained/specialized from.
        derivation:
          type: string
          enum: [specialization,constraint]
          description: How relates to base definition. [TypeDerivationRule](http://www.hl7.org/fhir/valueset-type-derivation-rule.html).
        snapshot:
          type: object
          description: Snapshot view of the structure.
          required: [element]
          properties:
            element:
              description: Definition of elements in the resource (if no StructureDefinition).
              type: array
              items: 
                $ref: '#/components/schemas/ElementDefinition'
        differential:
          type: object
          description: Differential view of the structure.
          required: [element]
          properties:
            element:
              description: Definition of elements in the resource (if no StructureDefinition).
              type: array
              items: 
                $ref: '#/components/schemas/ElementDefinition'          
         

  examples:
    Condition:  
      value:
        resourceType: Condition
        meta:
          profile:
          - http://ehealth.ua/fhir/StructureDefinition/Condition
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233
        recorder:
          identifier: 
            system: https://ehealth.ua/Employees
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        asserter:
          identifier: 
            system: https://ehealth.ua/Employees
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        encounter:
          reference: http://ehealth.ua/fhir/Encounter/9183a36b-4d45-4244-9339-63d81cd08d9c
        code:
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/ICD10
            code: A00.0
        clinicalStatus: 
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_clinical_statuses
            code: active
        verificationStatus: 
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_verification_statuses
            code: confirmed
        severity:
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_severities
            code: mild
        bodySite:
          coding:
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/body_sites
            code: 106004
        onsetDateTime: 2018-10-08T09:46:37.694Z
        recordedDate: 2018-10-08T09:46:37.694Z
        stage:
          summary:
            coding:
              system: http://ehealth.ua/fhir/CodeSystem/eHealth/condition_stages
              code: 260998006
        evidences:
          code:
            coding:
              system: http://ehealth.ua/fhir/CodeSystem/eHealth/ICPC2/reasons
              code: B41
          detail:
            reference: http://ehealth.ua/fhir/Observation/9183a36b-4d45-4244-9339-63d81cd08d9c
    Observation:
      value:
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        resourceType: Observation
        meta:
          profile:
          - http://ehealth.ua/fhir/StructureDefinition/Observation
        status: valid
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233
        performer:
          identifier: 
            system: https://ehealth.ua/Employees
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e     
        partOf:
          reference: http://ehealth.ua/fhir/DiagnosticReport/9183a36b-4d45-4244-9339-63d81cd08d9c
        category: 
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_categories
                code: survey
        code: 
          - coding: 
              - system: http://loinc.org
                code: 10010-7
        encounter:
          reference: http://ehealth.ua/fhir/Encounter/9183a36b-4d45-4244-9339-63d81cd08d9c
        effectiveDateTime: 2013-04-02T09:30:10+01:00
        issued: 2013-04-02T09:30:10+01:00
        interpretation:
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_interpretations
                code: L
        note:
          text: "To see the world in a grain of sand, and to see heaven in a wild flower, hold infinity in the palm of your hands, and eternity in an hour."
        bodySite:
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/body_sites
                code: 106004
        method:
          - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_method
                code: 115341008
        valueQuantity:
          value: 0
          comparator: >
          unit: mg
          system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
          code: mg
        referenceRange:
          low:
            value: 0
            comparator: >
            unit: mg
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
            code: mg
          high:
            value: 0
            comparator: >
            unit: mg
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
            code: mg
          type:
            - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/reference_range_types
                code: normal
          appliesTo:
            - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/reference_range_applications
                code: Male
          age:
            low:
              value: 18
              comparator: >
              unit: years
            high:
              value: 35
              comparator: <
              unit: years
        component:
          code:
            - coding: 
              - system: http://loinc.org
                code: 10569-2
          valueQuantity:
            value: 0
            comparator: >
            unit: mg
            system: http://ehealth.ua/fhir/CodeSystem/eHealth/ucum_units
            code: mg
          interpretation:
            - coding: 
              - system: http://ehealth.ua/fhir/CodeSystem/eHealth/observation_interpretations
                code: L
    Encounter:
      value:
        resourceType: Encounter
        meta:
          profile:
          - http://ehealth.ua/fhir/StructureDefinition/Encounter
        id: 465fb6fe-2dea-4b8a-9ef7-58379d1eaab0
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233       
        participant:
        - type:
            coding:
              - system: http://ehealth.edenlabllc.com/CodeSystem/participant-type
                code: PPRF
          individual:
            identifier: 
              system: https://ehealth.ua/Employees
              value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        status: finished
        date: 2018-08-02T10:45:16.000Z
        episodeOfCare:
          reference: http://ehealth.ua/fhir/EpisodeOfCare/9183a36b-4d45-4244-9339-63d81cd08d9c
        basedOn:
          reference: http://ehealth.ua/fhir/ServiceRequest/9183a36b-4d45-4244-9339-63d81cd08d9c
        class:
          system: http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_classes
          code: PHC
        type:
          coding:
          - system: http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_types
            code: field
        serviceProvider:
          reference: http://ehealth.ua/fhir/Organization/9183a36b-4d45-4244-9339-63d81cd08d9c
        diagnoses:
        - condition:
            reference: http://ehealth.ua/fhir/Condition/9183a36b-4d45-4244-9339-63d81cd08d9c
          use:
            coding:
            - system: http://ehealth.ua/fhir/CodeSystem/eHealth/diagnosis_roles
              code: primary
          rank: 1
        location:
          reference: http://ehealth.ua/fhir/Location/9183a36b-4d45-4244-9339-63d81cd08d9c
        hospitalization:
          admitSource:
            coding:
            - system: http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_admit_source
              code: EMD
          reAdmission:
            coding:
            - system: http://ehealth.edenlabllc.com/CodeSystem/eHealth/diagnosis_readmission
              code: R
        priority: 
          coding:
            - system: http://ehealth.edenlabllc.com/CodeSystem/eHealth/encounter_priority
              code: R
              
    TransactionRequest:
      value:  
        resourceType: Bundle
        type: transaction
        meta:
          profile:
          - https://ehealth.ua/fhir/StructureDefinition/transaction-bundle
        subject:
          identifier: 
            system: https://ehealth.ua/MPI
            value: f1ee0439-79be-4371-bf61-0b9066525233
        entry:
          - resource:
              $ref: '#/components/examples/Encounter/value'
            request: 
              method: POST
              url: Encounter
          - resource:
              $ref: '#/components/examples/Condition/value'
            request: 
              method: POST
              url: Condition